apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: yupaccount
  namespace: yup
---
kind: Role
metadata:
  creationTimestamp: null
  name: yuprole
  namespace: yup
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - events
  - secrets
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: yuprolebinding
  namespace: yup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: yuprole
subjects:
- kind: ServiceAccount
  name: yupaccount
  namespace: yup