# This helm values file defines app-based settings
# Charts use those values, so this file **MUST** be included in all chart releases

app:                                                    # app global settings
  name: "yup"                                      # Override for custom app name
  ingress:                                              # ingress related settings
    entries:
      procedimiento: procedimiento-api
      webgateway: webgateway-api
      web: ""                        # ingress entry for web
      yuptemplatehttpaggregator: yuptemplate-httpaggregator   # ingress entry for yuptemplate httpaggregator
  svc:
      yuptemplateapi: yuptemplate-api 
      procedimiento: procedimiento-api
      workflow: workflow-api
      webgateway: webgateway-api
      web: web                        # service name for web
      yuptemplatehttpaggregator: yuptemplate-httpaggregator # service name for yuptemplate httpaggregator