# This helm values file defines all infrastructure used.
# It is used on all charts, so ** MUST BE INCLUDED ** on every deployment

inf:
  mesh:
    enabled: false          # True to enable Linkerd (set by deploy-all.ps1)
  tls:
    enabled: false          # True to enable TLS (set by deploy-all.ps1)
    issuer: ""              # cert-manager issuer to use for retrieving certs (set by deploy-all.ps1)

  k8s:                      # inf.k8s defines Kubernetes cluster global config
    dns:  ""                # k8s external  DNS. This value or ip value MUST BE PROVIDED
    local: false            # True when deploying on "local K8s" provided by Docker Desktop.