# global config
global:
  env: 
    "ASPNETCORE_ENVIRONMENT": "Staging"
    "ASPNETCORE_FORWARDEDHEADERS_ENABLED": "true"
  # Environment variables shared between all the pods, populated with valueFrom: fieldRef
  envValuesFrom:
    Runtime__IpAddress: status.podIP

# config for test-app-api
test-app-api:
  replicaCount: 1

  image:
    repository: eduyupanqui/my-test-api
    pullPolicy: IfNotPresent
    tag: ""

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    hosts:
      - host: minikube.local
        paths: 
        - "/my-test-app(/|$)(.*)"

  autoscaling:
    enabled: false

  serviceAccount:
    create: false

# config for test-app-service
test-app-service:
  replicaCount: 1

  image:
    repository: eduyupanqui/my-test-service
    pullPolicy: IfNotPresent
    tag: ""

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: false

  autoscaling:
    enabled: false

  serviceAccount:
    create: false